# Generated by Django 5.1 on 2024-08-27 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="avatar/"
            ),
            preserve_default=False,
        ),
    ]
