# Generated by Django 5.1 on 2024-08-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="first_name",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="last_name",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
