# Generated by Django 5.1 on 2024-08-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_account_first_name_alter_account_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="image",
        ),
        migrations.AddField(
            model_name="account",
            name="avatar",
            field=models.ImageField(default="avatar/avatar.png", upload_to="avatar/"),
        ),
    ]
