# Generated by Django 5.1 on 2024-08-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("age", models.PositiveIntegerField()),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+ve", "A+ve"),
                            ("A-ve", "A-ve"),
                            ("B+ve", "B+ve"),
                            ("B-ve", "B-ve"),
                            ("AB+ve", "AB+ve"),
                            ("AB-ve", "AB-ve"),
                            ("O+ve", "O+ve"),
                            ("O-ve", "O-ve"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                ("phone", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
