# Generated by Django 5.1 on 2024-08-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0002_alter_patient_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.PositiveIntegerField(),
        ),
    ]
