# Generated by Django 5.1 on 2024-09-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0003_alter_patient_gender_alter_patient_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="avatar",
            field=models.ImageField(
                default="patients/avatar/avatar.png", upload_to="patients/avatar/"
            ),
        ),
    ]
